# Generated by Django 5.2.7 on 2025-10-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrequestboard',
            name='stage',
            field=models.CharField(choices=[('request_to_cradit', 'CRADIT-CARD REQUEST'), ('request_to_ACCEPT', 'CRADIT-CARD ACCEPT'), ('request_DEINE', 'CRADIT-CARD DEINE')]),
        ),
    ]
